### ISSUE TITLE
pcb 1.8 available?

### ISSUE THREAD

**Issue by adoeller** [VanceVagell/kv4p-ht#106]
Hi,

i already have the esp-board as well as the radio chip. all i need is the pcb with 7-8 resistors and capacitors.

is the improved v 1.8 design available with production files?

**Comment by SmittyHalibut** [comment]
Not yet.  The most recent version is v1.7b, but it's got some weirdness with the ESP module spacing.  I need to make a v1.7c that fixes that, and makes it work a bit better with different modules.  Watch #59 for progress on that.

Closing because I think I answered your question.  If you have follow up questions, by all means reopen.
