### ISSUE TITLE
Is M17 possible with this hardware?

### ISSUE THREAD

**Issue by AbortRetryFail** [VanceVagell/kv4p-ht#27]
There's plenty of processor power in a smartphone to do all the DSP work, but is the radio chip up to the task?

**Comment by Bastiti** [comment]
No, you'll need to replace DRA818 with SA818

**Comment by VanceVagell** [comment]
I really wanted to add M17 support, but I spoke with one of the creators and apparently it would require people to flash the radio module itself, not just the ESP32. That is far more advanced than I want the mainline version of this project to get.

That said, if someone wants to create a more advanced variant of the project that implements this, that would be really awesome (and I'd probably play around with it myself!). 

Closing this out because I believe it is infeasible for the mainline kv4p HT project.
