### ISSUE TITLE
Android enhancements: Vol PTT button 

### ISSUE THREAD

**Issue by chengmania** [VanceVagell/kv4p-ht#75]
Adding an option to have the PTT button as the Volume Down button.

**Comment by elitegoodguy** [comment]
Is that a good idea?  I guess it depends on how it's implemented... What if it's too loud and I need to turn down the volume. I might key up?

**Comment by chengmania** [comment]
Maybe a graphical volume slider.  I just thinking along the lines of a physical PTT button.

**Comment by p1973rsr911** [comment]
I also think adding pads to the board for an external PTT button would be a great idea.

**Comment by VanceVagell** [comment]
The new PCBs that @SmittyHalibut is working on will have pads for optional hardware PTT buttons, and we'll add software support for that when those are available.

I'm reluctant to make the volume buttons do this, because people might get frustrated if the radio is being noisy and they can't figure out how to turn it down (forgetting they had enabled this).

**Comment by simeneide** [comment]
hi @VanceVagell and @SmittyHalibut : did these hardware ppt buttons come into realization? :)
